(()=>{
const $=id=>document.getElementById(id), patterns={'32':[0,3,6,10,12],'23':[2,4,8,11,14]};
let ctx,master,running=false,timer,raf,next=0,step=0,queue=[],nodes=new Set(),generation=0;
function draw(){const hits=patterns[$('clave-direction').value];$('clave-grid').replaceChildren();for(let i=0;i<16;i++){const cell=document.createElement('span');cell.className='clave-step';cell.textContent=i%2?'&':String(i%8/2+1);const dot=document.createElement('b');dot.textContent=hits.includes(i)?'●':'·';cell.append(dot);cell.setAttribute('aria-label','Bar '+(i<8?1:2)+', '+(i%2?'and of '+(Math.floor(i%8/2)+1):'beat '+(i%8/2+1))+(hits.includes(i)?', clave stroke':', rest'));$('clave-grid').append(cell);}$('clave-counts').textContent=$('clave-direction').value==='32'?'Bar 1: 1, & of 2, 4 · Bar 2: 2, 3':'Bar 1: 2, 3 · Bar 2: 1, & of 2, 4';}
function tone(time,beat=false){const o=ctx.createOscillator(),g=ctx.createGain();o.type=beat?'sine':'triangle';o.frequency.setValueAtTime(beat?480:1800,time);g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(beat?.12:.45,time+.001);g.gain.exponentialRampToValueAtTime(.0001,time+.055);o.connect(g);g.connect(master);nodes.add(o);o.onended=()=>{nodes.delete(o);o.disconnect();g.disconnect();};o.start(time);o.stop(time+.06);}
function schedule(){if(!running)return;while(next<ctx.currentTime+.1){if(patterns[$('clave-direction').value].includes(step))tone(next);if($('clave-pulse').checked&&step%2===0)tone(next,true);queue.push({step,time:next});next+=30/Number($('clave-tempo').value);step=(step+1)%16;}}
function animate(){if(!running)return;let latest;while(queue.length&&queue[0].time<=ctx.currentTime)latest=queue.shift();if(latest)Array.from($('clave-grid').children).forEach((c,i)=>c.classList.toggle('current',i===latest.step));raf=requestAnimationFrame(animate);}
function stop(){generation++;running=false;clearInterval(timer);cancelAnimationFrame(raf);for(const o of nodes){try{o.stop();}catch{}}nodes.clear();queue=[];$('clave-start').textContent='▶ Start';$('clave-start').setAttribute('aria-pressed','false');$('clave-status').textContent='Stopped. Start again from the first bar.';Array.from($('clave-grid').children).forEach(c=>c.classList.remove('current'));}
async function start(){const token=++generation;$('clave-start').disabled=true;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error();if(!ctx){ctx=new Audio();master=ctx.createGain();master.connect(ctx.destination);}await ctx.resume();if(token!==generation)return;master.gain.value=Number($('clave-volume').value)/100;running=true;step=0;next=ctx.currentTime+.06;queue=[];$('clave-start').textContent='■ Stop';$('clave-start').setAttribute('aria-pressed','true');$('clave-status').textContent='Playing. Clap the filled dots; keep your foot on the beat.';schedule();timer=setInterval(schedule,25);animate();}catch{stop();$('clave-status').textContent='Audio could not start. Try again in a browser with sound enabled.';}finally{$('clave-start').disabled=false;}}
$('clave-start').onclick=()=>running?stop():start();
$('clave-direction').onchange=()=>{stop();draw();};
$('clave-tempo').oninput=()=>{$('clave-bpm').textContent=$('clave-tempo').value;};
$('clave-volume').oninput=()=>{if(master)master.gain.setTargetAtTime(Number($('clave-volume').value)/100,ctx.currentTime,.01);};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',stop);draw();
})();
